upgpkg: llvm 6.0.0-4
Add missing header to InstructionCombining.cpp; fixes Crystal build
which failed with "undefined reference to 'LLVMInitializeInstCombine'"

https://bugs.llvm.org/show_bug.cgi?id=35947

git-svn-id: file:///srv/repos/svn-packages/svn@319528 eb2447ed-0c53-47e4-bac8-5bc4a241df78